name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Railway
        run: railway up --service=64bbd0e5-a64f-4494-8731-1852d6bf90eb
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
